## 2. Write a class that implements a matrix.

 

You are allowed to use external libraries for the internal implementation.

Each sub-task of this one should be in a separate cell.



### 2.1 Implement the Matrix class with a standard constructor.

The matrix must be such that the following code works (e.g. in a notebook cell).

 

 

```

k=3

l=4

m=5

A=Matrix(k, l)

B=Matrix(l, m)

```

**First Matrix A and Second Matrix B**

In [ ]:
import math
from math import sqrt
import numbers
import numpy as np

class Matrix(object):
    # Constructor
    def __init__(self, k, l, m):
      self.row_A = k
      self.col_A = l
      self.row_B = l
      self.col_B = m
          
    def Matrix_items_A(self, m_A):
      m_A = np.empty((self.row_A, self.col_A))
      for i in range(self.row_A):
        for j in range(self.col_A):
          y_A = input("Enter value ")
          m_A[i,j] = y_A
      return m_A
    def Matrix_items_B(self, m_B):
      m_B = np.empty((self.row_B, self.col_B))
      for i in range(self.row_B):
        for j in range(self.col_B):
          y_B = input("Enter value ")
          m_B[i,j] = y_B
      return m_B


In [ ]:
y1_A = Matrix(3,4,5)
A = y1_A.Matrix_items_A(m)
print("The contents of the first matrix is \n", A)
B = y1_A.Matrix_items_B(m)
print("The contents of the first matrix is \n", B)

Enter value 3
Enter value 5
Enter value 6
Enter value 9
Enter value 0
Enter value 4
Enter value 5
Enter value 6
Enter value 7
Enter value 3
Enter value 2
Enter value 5
The contents of the first matrix is 
 [[3. 5. 6. 9.]
 [0. 4. 5. 6.]
 [7. 3. 2. 5.]]
Enter value 7
Enter value 6
Enter value 0
Enter value 0
Enter value 3
Enter value 5
Enter value 7
Enter value 9
Enter value 1
Enter value 0
Enter value 2
Enter value 0
Enter value 0
Enter value 7
Enter value 5
Enter value 4
Enter value 4
Enter value 3
Enter value 0
Enter value 2
The contents of the first matrix is 
 [[7. 6. 0. 0. 3.]
 [5. 7. 9. 1. 0.]
 [2. 0. 0. 7. 5.]
 [4. 4. 3. 0. 2.]]


### 2.2 Implement methods for Matrix dimensions.

 

Implement methods in the Matrix class so that the following code works.

 

```

k=3

l=4

m=5

A=Matrix(k, l)

B=Matrix(l, m)

assert A.ncols == B.nrows

```

In [ ]:
import math
from math import sqrt
import numbers
import numpy as np

class Matrix(object):
    # Constructor
    def __init__(self, k, l, m):
      self.row_A = k
      self.col_A = l
      self.row_B = l
      self.col_B = m
          
    def Matrix_items_A(self, m_A):
      m_A = np.empty((self.row_A, self.col_A))
      for i in range(self.row_A):
        for j in range(self.col_A):
          y_A = input("Enter value ")
          m_A[i,j] = y_A
      return m_A
    def Matrix_items_B(self, m_B):
      m_B = np.empty((self.row_B, self.col_B))
      for i in range(self.row_B):
        for j in range(self.col_B):
          y_B = input("Enter value ")
          m_B[i,j] = y_B
      return m_B
    def assert_check(x, y):
      if x==y:
        print("The column of Matrix A is equal to Matrix of B")

In [ ]:
y1_A = Matrix(3,4,5)
A = y1_A.Matrix_items_A(m)
x_A, y_A = A.shape
B = y1_A.Matrix_items_B(m)
x_B, y_B = B.shape
Y = Matrix.assert_check(y_A, x_B)

Enter value 0
Enter value 1
Enter value 2
Enter value 3
Enter value 4
Enter value 5
Enter value 6
Enter value 7
Enter value 8
Enter value 9
Enter value 1
Enter value 2
Enter value 2
Enter value 3
Enter value 4
Enter value 4
Enter value 1
Enter value 3
Enter value 4
Enter value 5
Enter value 6
Enter value 7
Enter value 8
Enter value 9
Enter value 0
Enter value 3
Enter value 5
Enter value 6
Enter value 8
Enter value 9
Enter value 2
Enter value 1
The column of Matrix A is equal to Matrix of B


### 2.3 Implement Matrix multiplication.

 

Implement methods in the Matrix class so that the following code works.

 

```

k=3

l=4

m=5

A=Matrix(k, l)

B=Matrix(l, m)

assert A.ncols == B.nrows

C = A * B

```

In [ ]:
class Matrix_mul(object):
    # Constructor
    def __init__(self, A, B):
      self.A = A
      self.B = B
     
    def matrix_mul_f(self):
      result = np.empty((3, 5))
      for i in range(len(self.A)):
        
        for j in range(len(self.B[0])):
         
          for k in range(len(self.B)):
            result[i][j] += self.A[i][k] * self.B[k][j]
      return result


In [ ]:
OP = Matrix_mul(A, B)
result_ = OP.matrix_mul_f()
result_=result_.astype(np.int)
print(result_.shape)
print(result_)

(3, 5)
[[                 148                  184                  128
                    72                   80]
 [                 452                  568                  416
                   312                  304]
 [                 252                  340                  380
  -9223372036854775808                  312]]


# **References**



1.   https://docs.python.org/3/tutorial/classes.html
2.   https://code.activestate.com/recipes/578131-a-simple-matrix-class/
3.  https://stackoverflow.com/questions/48147950/matrix-class-test

